-- Notification center: persisted per-store notifications generated by domain events
-- Applied directly to Supabase via MCP on 2026-07-11.

CREATE TABLE IF NOT EXISTS notifications (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id    UUID        NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  user_id     UUID        REFERENCES users(id) ON DELETE SET NULL,
  type        TEXT        NOT NULL,
  title       TEXT        NOT NULL,
  body        TEXT        NOT NULL,
  link        TEXT,
  metadata    JSONB       NOT NULL DEFAULT '{}',
  read_at     TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS notifications_store_unread_idx
  ON notifications(store_id)
  WHERE read_at IS NULL;

CREATE INDEX IF NOT EXISTS notifications_store_recent_idx
  ON notifications(store_id, created_at DESC);

CREATE INDEX IF NOT EXISTS notifications_user_idx
  ON notifications(user_id)
  WHERE user_id IS NOT NULL;
