import "server-only"
import type { DbClient } from "../db"
import type { Order, Prisma } from "../../generated/prisma/client"

/**
 * Pure data access for the `orders` table. No business rules here. No
 * delete method — DATA_MODEL.md: Orders are never physically deleted, they
 * are the permanent record of what happened; cancellation is a status
 * transition (`update`), not a row removal.
 */
export const orderRepository = {
  findById(db: DbClient, id: string): Promise<Order | null> {
    return db.order.findUnique({ where: { id } })
  },

  exists(db: DbClient, id: string): Promise<boolean> {
    return db.order.findUnique({ where: { id }, select: { id: true } }).then(Boolean)
  },

  findByIdWithDetails(db: DbClient, id: string) {
    return db.order.findUnique({
      where: { id },
      include: {
        items: true,
        statusTransitions: { orderBy: { occurredAt: "desc" } },
        kitchenTicket: true,
        payment: true,
        delivery: true,
      },
    })
  },

  /** `(store_id, number)` is unique — the human-readable order reference. */
  findByStoreAndNumber(db: DbClient, storeId: string, number: number): Promise<Order | null> {
    return db.order.findUnique({ where: { storeId_number: { storeId, number } } })
  },

  /** Includes the Customer's `name`/`phone` — API_SPEC.md's list shape denormalizes these onto each row. */
  findManyByStore(
    db: DbClient,
    storeId: string,
    params: {
      where?: Prisma.OrderWhereInput
      orderBy?: Prisma.OrderOrderByWithRelationInput
      skip?: number
      take?: number
    } = {},
  ) {
    return db.order.findMany({
      where: { storeId, ...params.where },
      orderBy: params.orderBy ?? { createdAt: "desc" },
      skip: params.skip,
      take: params.take,
      include: { customer: { select: { name: true, phone: true } } },
    })
  },

  count(db: DbClient, where: Prisma.OrderWhereInput): Promise<number> {
    return db.order.count({ where })
  },

  /**
   * Allocates the next sequential order number for a store, per
   * DATA_MODEL.md: "Generated by the service layer using an advisory lock."
   * `pg_advisory_xact_lock` is transaction-scoped and releases automatically
   * at COMMIT/ROLLBACK — the caller MUST invoke this with a transaction
   * client (i.e. from inside `prisma.$transaction(async (tx) => ...)`) so
   * the lock is held for the duration of the whole order-creation
   * transaction, not just this query.
   */
  async getNextOrderNumber(db: DbClient, storeId: string): Promise<number> {
    await db.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${storeId}))`
    const result = await db.$queryRaw<{ next_number: number }[]>`
      SELECT COALESCE(MAX("number"), 0) + 1 AS next_number
      FROM "orders"
      WHERE "store_id" = ${storeId}::uuid
    `
    return result[0].next_number
  },

  create(db: DbClient, data: Prisma.OrderCreateInput): Promise<Order> {
    return db.order.create({ data })
  },

  update(db: DbClient, id: string, data: Prisma.OrderUpdateInput): Promise<Order> {
    return db.order.update({ where: { id }, data })
  },
}
